// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeurkaikrhwzjdhbynoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldXJrYWlrcmh3empkaGJ5bm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mjc0NzksImV4cCI6MjA2NjQwMzQ3OX0.DDgyaurwz4kQ_v9EazsIyyO4JZ7wxZMkxLE7dQR4H8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);